class Solution:
    def minimumDistance(self, nums: List[int]) -> int:

        ### testing llama.cpp; generated by gemma-4-26B-A4B-it-UD-Q4_K_M ###

        # Step 1: Group indices of each number using a dictionary
        index_map = defaultdict(list)
        for idx, val in enumerate(nums):
            index_map[val].append(idx)
        
        min_dist = float('inf')
        found = False
        
        # Step 2: Iterate through the dictionary to find good tuples
        for val in index_map:
            indices = index_map[val]
            
            # A good tuple requires at least 3 occurrences of the same number
            if len(indices) >= 3:
                found = True
                # Step 3: Check consecutive triplets in the sorted index list
                # The distance is 2 * (indices[i+2] - indices[i])
                for i in range(len(indices) - 2):
                    current_dist = 2 * (indices[i+2] - indices[i])
                    if current_dist < min_dist:
                        min_dist = current_dist
                        
        # Step 4: Return the minimum distance or -1 if no good tuple was found
        return min_dist if found else -1